<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJrgRgPE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJrgRgPE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJrgRgPE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJrgRgPE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJrgRgPE\App_KernelDevDebugContainer([
    'container.build_hash' => 'JrgRgPE',
    'container.build_id' => '835df1dc',
    'container.build_time' => 1689937662,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJrgRgPE');
