<?php

namespace ContainerGkc52xQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EGurrEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._EGurrE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._EGurrE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'euro' => ['privates', '.errored..service_locator._EGurrE.App\\Entity\\Euros', NULL, 'Cannot autowire service ".service_locator._EGurrE": it needs an instance of "App\\Entity\\Euros" but this type has been excluded in "config/services.yaml".'],
        ], [
            'euro' => 'App\\Entity\\Euros',
        ]);
    }
}
