<?php

namespace ContainerGkc52xQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ToRLdgOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ToRLdgO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ToRLdgO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['privates', '.errored.BPYewtG', NULL, 'Cannot determine controller argument for "App\\Controller\\RegisterController::index()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'em' => '?',
        ]);
    }
}
