<?php

namespace ContainerGkc52xQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEuros2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._EGurrE.App\Entity\Euros' shared service.
     *
     * @return \App\Entity\Euros
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._EGurrE": it needs an instance of "App\\Entity\\Euros" but this type has been excluded in "config/services.yaml".');
    }
}
